apiVersion: extensions/v1beta1
kind: Pod
metadata:
  name: achivement2
  namespace: ns-15
spec:
  replicas: 3
  selector:
    matchlabels:
      app: achivement2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: achivement2
        namespace: ns-15
    spec:
      containers:
        - name: achivement2
          namespace: ns-15
          image: maximeremindocker/achivement2:latest
          ports:
          - port: 80
          env:
          - name: APP_HOST
            value: localhost
          - name: APP_PORT
            value: 5000
          - name: DB_HOST
            value: localhost
          - name: DB_PORT
            value: 6379
          - name: DB_NAME
            value: Number