apiVersion: apps/v1
kind: Deployment
metadata:
  name: achivement2
  namespace: ns-15
spec:
  replicas: 3
  selector:
    matchlabels:
      app: achivement2
      tier: backend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: achivement2
        namespace: ns-15
        tier: backend
    spec:
      containers:
        - name: achivement2
          namespace: ns-15
          image: maximeremindocker/achivement2:latest
          resources:
          limits:
            memory: "2048Mi"
            cpu: "1000m"
          ports:
          - containerPort: 80
          env:
          - name: APP_HOST
            value: "0.0.0.0"
          - name: APP_PORT
            value: "5000"
          - name: DB_HOST
            value: redis
          - name: DB_PORT
            value: "6379"
          - name: DB_NAME
            value: Number