version: "3"

services: 
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass
    ports:
      - 27017:27017
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass
    depends_on:
      - mongo
  achivement2:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "5000:80"
    environment:
      - APP_HOST=localhost
      - APP_PORT=5000
      - DB_HOST=localhost
      - DB_PORT=27017
      - DB_NAME=Number

    