version: "3"

networks:
  app-tier:
    driver: bridge

services:
  redis:
    image: redis:latest
    container_name: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    expose:
      - "6379"
    ports:
      - "6379:6379"
    networks:
      - app-tier

  achivement2:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: achivement2:latest
    container_name: achivement2
    ports:
      - "5000:5000"
    links:
      - "redis"
    expose:
      - "5000"
    environment:
      - APP_HOST=0.0.0.0
      - APP_PORT=5000
      - DB_HOST=redis
      - DB_PORT=6379
      - DB_NAME=Number
    networks:
      - app-tier
    depends_on:
    - "redis"

    